# Generated by Django 5.1.1 on 2024-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('value_normalized', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('date_from', models.DateField()),
                ('date_until', models.DateField()),
                ('date_published', models.DateField(blank=True, null=True)),
                ('date_updated', models.DateField()),
                ('is_forecast', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'publishes',
                'managed': False,
            },
        ),
    ]
