country_codes = {
    "OECD_countries": {
        "AUS": "Australia",
        "AUT": "Austria",
        "BEL": "Belgium",
        "CAN": "Canada",
        "CHL": "Chile",
        "COL": "Colombia",
        "CRI": "Costa Rica",
        "CZE": "Czechia",
        "DNK": "Denmark",
        "EST": "Estonia",
        "FIN": "Finland",
        "FRA": "France",
        "DEU": "Germany",
        "GRC": "Greece",
        "HUN": "Hungary",
        "ISL": "Iceland",
        "IRL": "Ireland",
        "ISR": "Israel",
        "ITA": "Italy",
        "JPN": "Japan",
        "KOR": "Korea",
        "LVA": "Latvia",
        "LTU": "Lithuania",
        "LUX": "Luxembourg",
        "MEX": "Mexico",
        "NLD": "Netherlands",
        "NZL": "New Zealand",
        "NOR": "Norway",
        "POL": "Poland",
        "PRT": "Portugal",
        "SVK": "Slovak Republic",
        "SVN": "Slovenia",
        "ESP": "Spain",
        "SWE": "Sweden",
        "CHE": "Switzerland",
        "TUR": "Turkey",
        "GBR": "United Kingdom",
        "USA": "United States"
    },
    "Country_groupings": {
        "EA17": "Euro area (17 OECD countries)",
        "OECD": "Total OECD"
    },
    "Non_OECD_member_countries": {
        "ARG": "Argentina",
        "BRA": "Brazil",
        "BGR": "Bulgaria",
        "CHN": "China",
        "HRV": "Croatia",
        "IND": "India",
        "IDN": "Indonesia",
        "PER": "Peru",
        "ROU": "Romania",
        "RUS": "Russia",
        "ZAF": "South Africa"
    },
    "Non_OECD_trade_regions": {
        "DAE": "Dynamic Asian Economies (Chinese Taipei, Hong Kong, Malaysia, Philippines, Singapore, Thailand, Vietnam)",
        "OIL_SAU_O": "Other oil producers (Algeria, Angola, Azerbaijan, Bahrain, Brunei Darussalam, Chad, Democratic Republic of the Congo, Ecuador, Equatorial Guinea, Gabon, Iran, Iraq, Kazakhstan, Kuwait, Libya, Nigeria, Oman, Qatar, Saudi Arabia, South Sudan, Timor-Leste, Trinidad and Tobago, Turkmenistan, United Arab Emirates, Venezuela, Yemen)",
        "W_O": "Rest of the world"
    }
}