# Generated by Django 5.1.1 on 2024-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('instid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(blank=True, max_length=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('type', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'institutions',
                'managed': False,
            },
        ),
    ]
