-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.area
(
    areaid character varying(36) COLLATE pg_catalog."default" NOT NULL,
    name character varying(480) COLLATE pg_catalog."default" NOT NULL,
    description character varying(480) COLLATE pg_catalog."default",
    CONSTRAINT area_pkey PRIMARY KEY (areaid)
);

CREATE TABLE IF NOT EXISTS public.indicators
(
    inst_instid character varying(8) COLLATE pg_catalog."default" NOT NULL,
    indicid character varying(32) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    abbreviation character varying(32) COLLATE pg_catalog."default" NOT NULL,
    unit_measure character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT indicators_pkey PRIMARY KEY (indicid, inst_instid)
);

CREATE TABLE IF NOT EXISTS public.institutions
(
    instid character varying(8) COLLATE pg_catalog."default" NOT NULL,
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    abbreviation character varying(8) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    url character varying(120) COLLATE pg_catalog."default",
    country character varying(3) COLLATE pg_catalog."default",
    type character varying(3) COLLATE pg_catalog."default",
    CONSTRAINT institutions_pkey PRIMARY KEY (instid)
);

CREATE TABLE IF NOT EXISTS public.publishes
(
    inst_instid character varying(8) COLLATE pg_catalog."default" NOT NULL,
    indic_indicid character varying(36) COLLATE pg_catalog."default" NOT NULL,
    area_areaid character varying(36) COLLATE pg_catalog."default" NOT NULL,
    value numeric NOT NULL,
    value_normalized numeric,
    date_from date NOT NULL,
    date_until date NOT NULL,
    date_published date,
    date_updated date NOT NULL,
    is_forecast character(1) COLLATE pg_catalog."default" NOT NULL,
    --CONSTRAINT publishes_pkey PRIMARY KEY (inst_instid, indic_indicid, area_areaid, date_from, date_until, is_forecast)
);

ALTER TABLE IF EXISTS public.indicators
    ADD CONSTRAINT indicators_inst_instid_fkey FOREIGN KEY (inst_instid)
    REFERENCES public.institutions (instid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.publishes
    ADD CONSTRAINT publishes_area_areaid_fkey FOREIGN KEY (area_areaid)
    REFERENCES public.area (areaid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.publishes
    ADD CONSTRAINT publishes_indicators_indicid_fkey FOREIGN KEY (inst_instid, indic_indicid)
    REFERENCES public.indicators (inst_instid,indicid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;