# Generated by Django 5.1.1 on 2024-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=480)),
                ('description', models.CharField(blank=True, max_length=480, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
    ]
